--
-- PostgreSQL database dump
--

\restrict Rq3VIlIiDXoV0RmL9t46OPO3l323l9OiPH8j2goEeHHN5j3p6qnZoSAoph9752k

-- Dumped from database version 17.4
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: delete_old_pending_questions(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.delete_old_pending_questions() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM public.pending_questions WHERE phone = NEW.phone;
  RETURN NEW;
END;
$$;


--
-- Name: get_user_status(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_user_status(p_telefone text) RETURNS json
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_status_assinatura BOOLEAN;
    v_trial_status TEXT;
    v_trial_fim TIMESTAMPTZ;
    v_estado_conversa TEXT;
BEGIN
    -- 1. Verifica o status da assinatura na tabela de usuários
    SELECT
        assinatura_ativa INTO v_status_assinatura
    FROM
        public.users
    WHERE
        telefone = p_telefone;

    -- 2. Verifica o status do free trial (COLUNA CORRIGIDA AQUI)
    SELECT
        status_teste, data_fim INTO v_trial_status, v_trial_fim
    FROM
        public.free_trials
    WHERE
        usuario_telefone = p_telefone;

    -- 3. Verifica o estado atual da conversa
    SELECT
        estado_atual INTO v_estado_conversa
    FROM
        public.estados_conversa
    WHERE
        usuario_telefone = p_telefone;

    -- 4. Constrói e retorna o objeto JSON com os resultados
    RETURN json_build_object(
        'assinatura_ativa', COALESCE(v_status_assinatura, FALSE),
        'trial_status', v_trial_status,
        'trial_fim', v_trial_fim,
        'estado_conversa', v_estado_conversa
    );
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dietas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dietas (
    id bigint NOT NULL,
    calorias_diarias numeric,
    proteina_gramas numeric,
    carboidrato_gramas numeric,
    gordura_gramas numeric,
    data_criacao timestamp with time zone DEFAULT timezone('utc'::text, now()),
    usuario_telefone text NOT NULL,
    usuario_id uuid,
    gasto_basal bigint,
    tbm bigint,
    neat bigint,
    meta_base bigint,
    saldo_hoje numeric,
    meta_alvo integer
);


--
-- Name: dietas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dietas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dietas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estados_conversa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_conversa (
    id bigint NOT NULL,
    usuario_id uuid,
    estado_atual text,
    dados_contexto text,
    usuario_telefone text
);


--
-- Name: estados_conversa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estados_conversa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_conversa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: free_trials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.free_trials (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    usuario_id uuid,
    data_inicio timestamp with time zone DEFAULT now(),
    data_fim timestamp with time zone,
    status_teste text,
    data_conversao timestamp with time zone,
    usuario_telefone text NOT NULL
);


--
-- Name: free_trials_with_day; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.free_trials_with_day AS
 SELECT id,
    usuario_id,
    data_inicio,
    data_fim,
    status_teste,
    data_conversao,
    usuario_telefone,
    ((CURRENT_DATE - (data_inicio)::date) + 1) AS current_trial_day
   FROM public.free_trials;


--
-- Name: leads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leads (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nome text NOT NULL,
    email text NOT NULL,
    telefone text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: magic_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.magic_links (
    token uuid NOT NULL,
    phone text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone
);


--
-- Name: pending_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_questions (
    id bigint NOT NULL,
    phone text,
    question text,
    status text,
    calories numeric,
    protein numeric,
    carbs numeric,
    fat numeric
);


--
-- Name: pending_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pending_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pending_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registros_alimentares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_alimentares (
    id bigint NOT NULL,
    usuario_id uuid,
    nome_alimento text,
    calorias numeric,
    proteinas numeric,
    carboidratos numeric,
    gorduras numeric,
    tipo_refeicao text,
    data_consumo date,
    hora_consumo time without time zone,
    usuario_telefone text
);


--
-- Name: registros_alimentares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registros_alimentares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registros_alimentares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registros_treino; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_treino (
    id integer NOT NULL,
    usuario_telefone character varying(20) NOT NULL,
    data_treino date DEFAULT CURRENT_DATE NOT NULL,
    tipo_treino character varying(100) NOT NULL,
    duracao_minutos integer NOT NULL,
    intensidade character varying(20) NOT NULL,
    calorias_queimadas integer NOT NULL,
    observacoes text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: registros_treino_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registros_treino_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: registros_treino_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.registros_treino_id_seq OWNED BY public.registros_treino.id;


--
-- Name: saldo_calorico_diario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saldo_calorico_diario (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    usuario_telefone text NOT NULL,
    data_registro date NOT NULL,
    saldo_calorico integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    meta_alvo integer
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    telefone text NOT NULL,
    nome text,
    email text,
    tem_dieta_previa boolean,
    altura integer,
    peso numeric,
    idade integer,
    sexo text,
    nivel_atividade text,
    objetivo text,
    assinatura_ativa boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    preenchido boolean DEFAULT false NOT NULL,
    stripe_customer_id text,
    stripe_subscription_id text,
    stripe_subscription_status text,
    imc numeric GENERATED ALWAYS AS (round((peso / (((altura)::numeric / 100.0) * ((altura)::numeric / 100.0))), 2)) STORED
);


--
-- Name: workflow_locks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_locks (
    phone text NOT NULL
);


--
-- Name: registros_treino id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_treino ALTER COLUMN id SET DEFAULT nextval('public.registros_treino_id_seq'::regclass);


--
-- Name: dietas dietas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dietas
    ADD CONSTRAINT dietas_pkey PRIMARY KEY (usuario_telefone);


--
-- Name: estados_conversa estados_conversa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_conversa
    ADD CONSTRAINT estados_conversa_pkey PRIMARY KEY (id);


--
-- Name: estados_conversa estados_conversa_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_conversa
    ADD CONSTRAINT estados_conversa_usuario_id_key UNIQUE (usuario_id);


--
-- Name: free_trials free_trials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.free_trials
    ADD CONSTRAINT free_trials_pkey PRIMARY KEY (id, usuario_telefone);


--
-- Name: leads leads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT leads_pkey PRIMARY KEY (id);


--
-- Name: magic_links magic_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.magic_links
    ADD CONSTRAINT magic_links_pkey PRIMARY KEY (token);


--
-- Name: pending_questions pending_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_questions
    ADD CONSTRAINT pending_questions_pkey PRIMARY KEY (id);


--
-- Name: registros_alimentares registros_alimentares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_alimentares
    ADD CONSTRAINT registros_alimentares_pkey PRIMARY KEY (id);


--
-- Name: registros_treino registros_treino_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_treino
    ADD CONSTRAINT registros_treino_pkey PRIMARY KEY (id);


--
-- Name: saldo_calorico_diario saldo_calorico_diario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldo_calorico_diario
    ADD CONSTRAINT saldo_calorico_diario_pkey PRIMARY KEY (id);


--
-- Name: saldo_calorico_diario unq_usuario_data; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldo_calorico_diario
    ADD CONSTRAINT unq_usuario_data UNIQUE (usuario_telefone, data_registro);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_telefone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_telefone_key UNIQUE (telefone);


--
-- Name: workflow_locks workflow_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_locks
    ADD CONSTRAINT workflow_locks_pkey PRIMARY KEY (phone);


--
-- Name: idx_registros_treino_usuario_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registros_treino_usuario_data ON public.registros_treino USING btree (usuario_telefone, data_treino);


--
-- Name: magic_links_expires_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX magic_links_expires_idx ON public.magic_links USING btree (expires_at);


--
-- Name: pending_questions on_new_pending_question; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_new_pending_question BEFORE INSERT ON public.pending_questions FOR EACH ROW EXECUTE FUNCTION public.delete_old_pending_questions();


--
-- Name: estados_conversa estados_conversa_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_conversa
    ADD CONSTRAINT estados_conversa_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: saldo_calorico_diario fk_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldo_calorico_diario
    ADD CONSTRAINT fk_usuario FOREIGN KEY (usuario_telefone) REFERENCES public.users(telefone) ON DELETE CASCADE;


--
-- Name: free_trials free_trials_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.free_trials
    ADD CONSTRAINT free_trials_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.users(id);


--
-- Name: registros_alimentares registros_alimentares_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_alimentares
    ADD CONSTRAINT registros_alimentares_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: magic_links Allow insert magic links; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow insert magic links" ON public.magic_links FOR INSERT TO anon WITH CHECK (true);


--
-- Name: magic_links Allow select own token; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow select own token" ON public.magic_links FOR SELECT TO anon USING (true);


--
-- Name: magic_links Allow update used_at; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow update used_at" ON public.magic_links FOR UPDATE TO anon USING (true) WITH CHECK (true);


--
-- PostgreSQL database dump complete
--

\unrestrict Rq3VIlIiDXoV0RmL9t46OPO3l323l9OiPH8j2goEeHHN5j3p6qnZoSAoph9752k

